# The language in this case has no bearing - we are going to be making use of conda.
language: generic

jobs:
  include:
    - os: osx

env:
    global:
        # Add the BINSTAR_TOKEN environment variable. (This is the "CI_upload2" token in anaconda.org web UI)
        #- secure: "" 
        
script:
    - source ./.travis_scripts/build_all;
      
